import { PROJECT_FILES } from '../config/paths.js';
import type { Manifest } from '../config/manifest.js';

export interface SetupManifestTemplateInput {
  remote: string;
  ref?: string;
}

export function setupManifestTemplate(input: SetupManifestTemplateInput): string {
  const refLine = input.ref ? `ref: ${input.ref}\n` : '';
  return `remote: ${input.remote}
${refLine}
output:
  memory: true
  rules: true
  settings_local: false

params: {}

include:
  tags: []

exclude:
  rules: []
`;
}

export function hookFallbackWarning(errorMessage: string): string {
  return `claude-remote-config warning: ${errorMessage}
Using existing generated claude-remote-config files for this session.
`;
}

export function initSummaryTemplate(manifest: Manifest, resolvedCommit: string): string {
  const lines = [
    'claude-remote-config initialized.',
    '',
    manifest.ref ? `Remote ref: ${manifest.ref}` : 'Remote ref: HEAD',
    `Resolved commit: ${resolvedCommit.slice(0, 8)}`,
    `Generated instructions: ${PROJECT_FILES.generatedMemory}`,
  ];

  if (manifest.output.rules) {
    lines.push(`Generated rules: ${PROJECT_FILES.generatedRulesDir}/`);
  }

  if (manifest.output.settings_local) {
    lines.push(`Generated local settings: ${PROJECT_FILES.settingsLocal}`);
  }

  lines.push('', 'Use the generated claude-remote-config instructions as active project guidance for this session.');

  return `${lines.join('\n')}\n`;
}

export interface MemoryTemplateInput {
  remote: string;
  requestedRef?: string;
  resolvedCommit: string;
  memorySources: string[];
  loadedRules: string[];
  contents: string[];
}

export function memoryTemplate(input: MemoryTemplateInput): string {
  const refLine = input.requestedRef ? `\nrequested_ref: ${input.requestedRef}` : '';
  return `<!--
Generated by claude-remote-config.
remote: ${input.remote}${refLine}
resolved_commit: ${input.resolvedCommit}

loaded_memory:
${input.memorySources.map((source) => `  - ${source}`).join('\n')}

loaded_rules:
${input.loadedRules.map((rule) => `  - ${rule}`).join('\n')}
-->

# Shared Claude Remote Config Instructions

${input.contents.join('\n\n').trim()}
`;
}

export function ruleGeneratedComment(id: string, version: string): string {
  return `<!-- generated by claude-remote-config from ${id}@${version} -->`;
}
