import { PROJECT_FILES } from '../config/paths.js';
import type { Manifest } from '../config/manifest.js';

export interface SetupManifestTemplateInput {
  remote: string;
  ref: string;
  profile: string;
}

export function setupManifestTemplate(input: SetupManifestTemplateInput): string {
  return `remote: ${input.remote}
ref: ${input.ref}
profile: ${input.profile}

materialize:
  memory: true
  rules: true
  settings_local: true

params: {}

include:
  tags: []

exclude:
  rules: []
`;
}

export function bridgeClaudeTemplate(): string {
  return `# Repo-specific Claude instructions

This repository uses claude-remote-config.

Generated shared instructions live at:

@../${PROJECT_FILES.generatedMemory}

## Local repo overrides

- Add repo-specific instructions here.
- These instructions are human-authored and committed.
`;
}

export function hookFallbackWarning(errorMessage: string): string {
  return `claude-remote-config warning: ${errorMessage}
Using existing generated claude-remote-config files for this session.
`;
}

export function initSummaryTemplate(manifest: Manifest, resolvedCommit: string): string {
  const lines = [
    'claude-remote-config initialized.',
    '',
    `Profile: ${manifest.profile}`,
    `Remote ref: ${manifest.ref}`,
    `Resolved commit: ${resolvedCommit.slice(0, 8)}`,
    `Generated instructions: ${PROJECT_FILES.generatedMemory}`,
  ];

  if (manifest.materialize.rules) {
    lines.push(`Generated rules: ${PROJECT_FILES.generatedRulesDir}/`);
  }

  if (manifest.materialize.settings_local) {
    lines.push(`Generated local settings: ${PROJECT_FILES.settingsLocal}`);
  }

  lines.push('', 'Use the generated claude-remote-config instructions as active project guidance for this session.');

  return `${lines.join('\n')}\n`;
}

export interface MemoryTemplateInput {
  remote: string;
  requestedRef: string;
  resolvedCommit: string;
  profile: string;
  memorySources: string[];
  loadedRules: string[];
  contents: string[];
}

export function memoryTemplate(input: MemoryTemplateInput): string {
  return `<!--
Generated by claude-remote-config.
remote: ${input.remote}
requested_ref: ${input.requestedRef}
resolved_commit: ${input.resolvedCommit}
profile: ${input.profile}

loaded_memory:
${input.memorySources.map((source) => `  - ${source}`).join('\n')}

loaded_rules:
${input.loadedRules.map((rule) => `  - ${rule}`).join('\n')}
-->

# Shared Claude Kit Instructions

${input.contents.join('\n\n').trim()}
`;
}

export function ruleGeneratedComment(id: string, version: string): string {
  return `<!-- generated by claude-remote-config from ${id}@${version} -->`;
}
