import { describe, expect, it } from 'vitest';
import { compileMemory, compileRule, substituteParams } from '../../src/output/compiler.js';
import { mergeSettings } from '../../src/output/settings.js';

describe('compiler', () => {
  it('substitutes parameters and validates missing values', () => {
    expect(substituteParams('Use {{ package_manager }}', { package_manager: 'pnpm' })).toBe('Use pnpm');
    expect(() => substituteParams('Use {{ missing }}', {})).toThrow(/missing parameter/i);
  });

  it('compiles memory with deterministic metadata', () => {
    const output = compileMemory({
      remote: 'git@example.com:org/rules.git',
      requestedRef: 'v1.0.0',
      resolvedCommit: 'abcdef123456',
      profile: 'node-service',
      memorySources: ['memory/base.md'],
      loadedRules: ['repo.hygiene@1.0.0'],
      contents: ['Base memory']
    });

    expect(output).toContain('Generated by claude-remote-config');
    expect(output).toContain('resolved_commit: abcdef123456');
    expect(output).toContain('Base memory');
  });

  it('compiles rules preserving only native paths frontmatter', () => {
    const output = compileRule({
      id: 'typescript.error-handling',
      version: '1.2.0',
      paths: ['src/**/*.ts'],
      body: 'Use {{ package_manager }}',
      params: { package_manager: 'pnpm' }
    });

    expect(output).toContain('paths:');
    expect(output).not.toContain('priority:');
    expect(output).toContain('typescript.error-handling@1.2.0');
    expect(output).toContain('Use pnpm');
  });
});

describe('mergeSettings', () => {
  it('merges settings fragments deeply', () => {
    expect(
      mergeSettings([
        { permissions: { allow: ['Bash(git status)'] }, hooks: ['a'], scalar: 'old' },
        { permissions: { allow: ['Bash(git status)', 'Read(*)'] }, hooks: ['b'], scalar: 'new' }
      ])
    ).toEqual({
      permissions: { allow: ['Bash(git status)', 'Read(*)'] },
      hooks: ['a', 'b'],
      scalar: 'new'
    });
  });
});
